// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using healthcare_api.Db;

#nullable disable

namespace healthcare_api.Migrations
{
    [DbContext(typeof(TrxDbContext))]
    [Migration("20260711062241_AddTeleconsultationMessage")]
    partial class AddTeleconsultationMessage
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "auth", "aal_level", new[] { "aal1", "aal2", "aal3" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "auth", "code_challenge_method", new[] { "s256", "plain" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "auth", "factor_status", new[] { "unverified", "verified" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "auth", "factor_type", new[] { "totp", "webauthn", "phone" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "auth", "oauth_authorization_status", new[] { "pending", "approved", "denied", "expired" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "auth", "oauth_client_type", new[] { "public", "confidential" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "auth", "oauth_registration_type", new[] { "dynamic", "manual" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "auth", "oauth_response_type", new[] { "code" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "auth", "one_time_token_type", new[] { "confirmation_token", "reauthentication_token", "recovery_token", "email_change_token_new", "email_change_token_current", "phone_change_token" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "realtime", "action", new[] { "INSERT", "UPDATE", "DELETE", "TRUNCATE", "ERROR" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "realtime", "equality_op", new[] { "eq", "neq", "lt", "lte", "gt", "gte", "in" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "storage", "buckettype", new[] { "STANDARD", "ANALYTICS", "VECTOR" });
            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "extensions", "pg_stat_statements");
            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "extensions", "pgcrypto");
            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "extensions", "uuid-ossp");
            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "vault", "supabase_vault");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("healthcare_api.Models.Transactional.Appointment", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime?>("AppointmentsDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Complaint")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<long?>("DoctorsId")
                        .HasColumnType("bigint");

                    b.Property<long?>("PatientsId")
                        .HasColumnType("bigint");

                    b.Property<long?>("QueueNumber")
                        .HasColumnType("bigint");

                    b.Property<string>("Status")
                        .HasColumnType("character varying");

                    b.HasKey("Id")
                        .HasName("Appointments_pkey");

                    b.HasIndex("DoctorsId");

                    b.HasIndex("PatientsId");

                    b.ToTable("Appointments");
                });

            modelBuilder.Entity("healthcare_api.Models.Transactional.Doctor", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<decimal?>("ConsultationFee")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Phone")
                        .HasColumnType("character varying");

                    b.Property<long?>("SpecializationId")
                        .HasColumnType("bigint");

                    b.Property<long?>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id")
                        .HasName("Doctors_pkey");

                    b.HasIndex("SpecializationId");

                    b.HasIndex("UserId");

                    b.ToTable("Doctors");
                });

            modelBuilder.Entity("healthcare_api.Models.Transactional.DoctorsSchedule", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("DayOfWeek")
                        .HasColumnType("text");

                    b.Property<long?>("DoctorsId")
                        .HasColumnType("bigint");

                    b.Property<TimeOnly?>("EndTime")
                        .HasColumnType("time without time zone");

                    b.Property<TimeOnly?>("StartTime")
                        .HasColumnType("time without time zone");

                    b.HasKey("Id")
                        .HasName("DoctorsSchedule_pkey");

                    b.HasIndex("DoctorsId");

                    b.ToTable("DoctorsSchedule", (string)null);
                });

            modelBuilder.Entity("healthcare_api.Models.Transactional.MedicalRecord", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long?>("AppointmentsId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Diagnosis")
                        .HasColumnType("text");

                    b.Property<long?>("DoctorsId")
                        .HasColumnType("bigint");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<long?>("PatientsId")
                        .HasColumnType("bigint");

                    b.Property<string>("Prescription")
                        .HasColumnType("text");

                    b.HasKey("Id")
                        .HasName("MedicalRecords_pkey");

                    b.HasIndex("AppointmentsId");

                    b.HasIndex("DoctorsId");

                    b.HasIndex("PatientsId");

                    b.ToTable("MedicalRecords");
                });

            modelBuilder.Entity("healthcare_api.Models.Transactional.Patient", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Address")
                        .HasColumnType("text");

                    b.Property<DateOnly?>("BirthDate")
                        .HasColumnType("date");

                    b.Property<string>("BloodType")
                        .HasColumnType("character varying");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Gender")
                        .HasColumnType("character varying");

                    b.Property<string>("Phone")
                        .HasColumnType("character varying");

                    b.Property<long?>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id")
                        .HasName("Patients_pkey");

                    b.HasIndex("UserId");

                    b.ToTable("Patients");
                });

            modelBuilder.Entity("healthcare_api.Models.Transactional.Specialization", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("character varying");

                    b.HasKey("Id")
                        .HasName("Specialization_pkey");

                    b.ToTable("Specialization", (string)null);
                });

            modelBuilder.Entity("healthcare_api.Models.Transactional.Teleconsultation", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long?>("AppointmentsId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTime?>("EndTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("StartTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Status")
                        .HasColumnType("character varying");

                    b.HasKey("Id")
                        .HasName("Teleconsultations_pkey");

                    b.HasIndex("AppointmentsId");

                    b.ToTable("Teleconsultations");
                });

            modelBuilder.Entity("healthcare_api.Models.Transactional.TeleconsultationMessage", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Content")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<long?>("SenderId")
                        .HasColumnType("bigint");

                    b.Property<long?>("TeleconsultationId")
                        .HasColumnType("bigint");

                    b.HasKey("Id")
                        .HasName("TeleconsultationMessages_pkey");

                    b.HasIndex("SenderId");

                    b.HasIndex("TeleconsultationId");

                    b.ToTable("TeleconsultationMessages");
                });

            modelBuilder.Entity("healthcare_api.Models.Transactional.User", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Email")
                        .HasColumnType("character varying");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("character varying");

                    b.Property<string>("Role")
                        .HasColumnType("character varying");

                    b.Property<string>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("character varying")
                        .HasDefaultValueSql("'Active'::character varying");

                    b.HasKey("Id")
                        .HasName("Users_pkey");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("healthcare_api.Models.Transactional.Appointment", b =>
                {
                    b.HasOne("healthcare_api.Models.Transactional.Doctor", "Doctors")
                        .WithMany("Appointments")
                        .HasForeignKey("DoctorsId")
                        .HasConstraintName("Appointments_DoctorsId_fkey");

                    b.HasOne("healthcare_api.Models.Transactional.Patient", "Patients")
                        .WithMany("Appointments")
                        .HasForeignKey("PatientsId")
                        .HasConstraintName("Appointments_PatientsId_fkey");

                    b.Navigation("Doctors");

                    b.Navigation("Patients");
                });

            modelBuilder.Entity("healthcare_api.Models.Transactional.Doctor", b =>
                {
                    b.HasOne("healthcare_api.Models.Transactional.Specialization", "Specialization")
                        .WithMany("Doctors")
                        .HasForeignKey("SpecializationId")
                        .HasConstraintName("Doctors_SpecializationId_fkey");

                    b.HasOne("healthcare_api.Models.Transactional.User", "User")
                        .WithMany("Doctors")
                        .HasForeignKey("UserId")
                        .HasConstraintName("Doctors_UserId_fkey");

                    b.Navigation("Specialization");

                    b.Navigation("User");
                });

            modelBuilder.Entity("healthcare_api.Models.Transactional.DoctorsSchedule", b =>
                {
                    b.HasOne("healthcare_api.Models.Transactional.Doctor", "Doctors")
                        .WithMany("DoctorsSchedules")
                        .HasForeignKey("DoctorsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("DoctorsSchedule_DoctorsId_fkey");

                    b.Navigation("Doctors");
                });

            modelBuilder.Entity("healthcare_api.Models.Transactional.MedicalRecord", b =>
                {
                    b.HasOne("healthcare_api.Models.Transactional.Appointment", "Appointments")
                        .WithMany("MedicalRecords")
                        .HasForeignKey("AppointmentsId")
                        .HasConstraintName("MedicalRecords_AppointmentsId_fkey");

                    b.HasOne("healthcare_api.Models.Transactional.Doctor", "Doctors")
                        .WithMany("MedicalRecords")
                        .HasForeignKey("DoctorsId")
                        .HasConstraintName("MedicalRecords_DoctorsId_fkey");

                    b.HasOne("healthcare_api.Models.Transactional.Patient", "Patients")
                        .WithMany("MedicalRecords")
                        .HasForeignKey("PatientsId")
                        .HasConstraintName("MedicalRecords_PatientsId_fkey");

                    b.Navigation("Appointments");

                    b.Navigation("Doctors");

                    b.Navigation("Patients");
                });

            modelBuilder.Entity("healthcare_api.Models.Transactional.Patient", b =>
                {
                    b.HasOne("healthcare_api.Models.Transactional.User", "User")
                        .WithMany("Patients")
                        .HasForeignKey("UserId")
                        .HasConstraintName("Patients_UserId_fkey");

                    b.Navigation("User");
                });

            modelBuilder.Entity("healthcare_api.Models.Transactional.Teleconsultation", b =>
                {
                    b.HasOne("healthcare_api.Models.Transactional.Appointment", "Appointments")
                        .WithMany("Teleconsultations")
                        .HasForeignKey("AppointmentsId")
                        .HasConstraintName("Teleconsultations_AppointmentsId_fkey");

                    b.Navigation("Appointments");
                });

            modelBuilder.Entity("healthcare_api.Models.Transactional.TeleconsultationMessage", b =>
                {
                    b.HasOne("healthcare_api.Models.Transactional.User", "Sender")
                        .WithMany("TeleconsultationMessages")
                        .HasForeignKey("SenderId")
                        .HasConstraintName("TeleconsultationMessages_SenderId_fkey");

                    b.HasOne("healthcare_api.Models.Transactional.Teleconsultation", "Teleconsultation")
                        .WithMany("TeleconsultationMessages")
                        .HasForeignKey("TeleconsultationId")
                        .HasConstraintName("TeleconsultationMessages_TeleconsultationId_fkey");

                    b.Navigation("Sender");

                    b.Navigation("Teleconsultation");
                });

            modelBuilder.Entity("healthcare_api.Models.Transactional.Appointment", b =>
                {
                    b.Navigation("MedicalRecords");

                    b.Navigation("Teleconsultations");
                });

            modelBuilder.Entity("healthcare_api.Models.Transactional.Doctor", b =>
                {
                    b.Navigation("Appointments");

                    b.Navigation("DoctorsSchedules");

                    b.Navigation("MedicalRecords");
                });

            modelBuilder.Entity("healthcare_api.Models.Transactional.Patient", b =>
                {
                    b.Navigation("Appointments");

                    b.Navigation("MedicalRecords");
                });

            modelBuilder.Entity("healthcare_api.Models.Transactional.Specialization", b =>
                {
                    b.Navigation("Doctors");
                });

            modelBuilder.Entity("healthcare_api.Models.Transactional.Teleconsultation", b =>
                {
                    b.Navigation("TeleconsultationMessages");
                });

            modelBuilder.Entity("healthcare_api.Models.Transactional.User", b =>
                {
                    b.Navigation("Doctors");

                    b.Navigation("Patients");

                    b.Navigation("TeleconsultationMessages");
                });
#pragma warning restore 612, 618
        }
    }
}
