// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using healthcare_api.Db;

#nullable disable

namespace healthcare_api.Migrations.RptDb
{
    [DbContext(typeof(RptDbContext))]
    partial class RptDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("healthcare_api.Models.Reporting.FactDoctorPerformance", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DoctorName")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<DateOnly?>("LastSyncDate")
                        .HasColumnType("date");

                    b.Property<int?>("Month")
                        .HasColumnType("int");

                    b.Property<string>("Specialization")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<int?>("TotalPatientsHandled")
                        .HasColumnType("int");

                    b.Property<int?>("TotalRevenueGenerated")
                        .HasColumnType("int");

                    b.Property<int?>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Fact_DoctorPerformances", (string)null);
                });

            modelBuilder.Entity("healthcare_api.Models.Reporting.FactMonthlyAppointment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateOnly?>("LastSyncDate")
                        .HasColumnType("date");

                    b.Property<int?>("Month")
                        .HasColumnType("int");

                    b.Property<int?>("TotalAppointments")
                        .HasColumnType("int");

                    b.Property<int?>("TotalCancelled")
                        .HasColumnType("int");

                    b.Property<int?>("TotalCompleted")
                        .HasColumnType("int");

                    b.Property<int?>("TotalOnSitesVisit")
                        .HasColumnType("int");

                    b.Property<int?>("TotalRevenue")
                        .HasColumnType("int");

                    b.Property<int?>("TotalTeleconsultations")
                        .HasColumnType("int");

                    b.Property<int?>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Fact_MonthlyAppointments", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
